---

- name: Checking if configuration for '{{ service }}' exist
  stat:
    path: "{{ docker_compose_run_remote_services_dir }}/{{ service }}"
  register: stat_remote_service_dir

- name: Absent docker-compose service '{{ service }}'
  docker_compose:
    project_src: "{{ docker_compose_run_remote_services_dir }}/{{ service }}"
    state: absent
  when: stat_remote_service_dir.stat.exists

- name: Delete service directory '{{ docker_compose_run_remote_services_dir }}/{{ service }}'
  file:
    path: "{{ docker_compose_run_remote_services_dir }}/{{ service }}"
    state: absent
  when: stat_remote_service_dir.stat.exists and docker_compose_run_action == 'absent-and-delete'
