---


- name: "Create main directory for all docker-compose services"
  file:
    path: "{{ docker_compose_run_remote_services_dir }}"
    state: directory
    owner: "root"


- include_tasks: services.yml
  loop: "{{ docker_compose_run_services_list }}"
  loop_control:
    loop_var: service

