---


- name: "Create main directory for all docker-compose services"
  file:
    path: "{{ docker_compose_run_remote_services_dir }}"
    state: directory
    owner: "root"


- include_tasks: services.yml
  loop: "{{ docker_compose_run_services_list }}"
  loop_control:
    loop_var: service





#- name: "Checking if individual directory exist"
#  stat:
#    path: "{{ docker_compose_run_local_individual_services_dir }}/{{ inventory_hostname }}"
#  register: stat_result
#  delegate_to: 127.0.0.1
#  become: no

#- debug:
#    var: stat_result

# - name: Only pull all necessary images
#   shell: |
#     cd "{{ thor_x_deploy_remote_docker_compose_dir }}"
#     docker-compose pull

# - name: Run docker-compose
#   docker_compose:
#     project_src: "{{ docker_compose_run_remote_services_dir }}/{{ item }}"
#     state: present
#   loop: "{{ docker_compose_run_services_list }}"

# - name: Prune all stopped containers
#   shell: docker container prune -f

# - name: Check docker-compose status
#   shell: |
#     cd "{{ thor_x_deploy_remote_docker_compose_dir }}"
#     docker-compose top
#   register: return_docker_compose_ps

# - name: Prune unusage images
#   shell: docker image prune -af
#   when:
#     - return_docker_compose_ps.stdout_lines
#     - thor_x_deploy_prune_images == true
