---

- name: "Checking if common configuration for '{{ service }}' exist"
  stat:
    path: "{{ docker_compose_run_local_common_services_dir }}/{{ service }}"
  register: stat_common_service_result
  delegate_to: 127.0.0.1
  become: no

- name: "Copy common configuration for '{{ service }}' service"
  copy:
    src: "{{ docker_compose_run_local_common_services_dir }}/{{ service }}"
    dest: "{{ docker_compose_run_remote_services_dir }}/"
    owner: "root"
    mode: "preserve"
  when: stat_common_service_result.stat.exists


- name: "Checking if individual configuration for '{{ service }}' exist"
  stat:
    path: "{{ docker_compose_run_local_individual_services_dir }}/{{ inventory_hostname }}/{{ service }}"
  register: stat_individual_service_result
  delegate_to: 127.0.0.1
  become: no

- include_tasks: individual-service.yml
  when: docker_compose_run_local_individual_services_dir != "" and stat_individual_service_result.stat.exists


- name: Get list files for service '{{ service }}'
  find:
    path: "{{ docker_compose_run_remote_services_dir }}/{{ service }}"
    recurse: yes
  register: find_list_files

- name: Replace variable %%inventory_hostname%%
  replace:
    path: "{{ item.path }}"
    regexp: '%%inventory_hostname%%'
    replace: "{{ inventory_hostname }}"
  loop: "{{ find_list_files.files }}"

- name: Replace variable %%ansible_host%%
  replace:
    path: "{{ item.path }}"
    regexp: '%%ansible_host%%'
    replace: "{{ ansible_host }}"
  loop: "{{ find_list_files.files }}"


- name: Only pull all necessary images for {{ service }}
  shell: |
    cd "{{ docker_compose_run_remote_services_dir }}/{{ service }}"
    docker-compose pull
  when: docker_compose_run_only_pull_images|bool == true

- name: Run service '{{ service }}'
  docker_compose:
    project_src: "{{ docker_compose_run_remote_services_dir }}/{{ service }}"
    state: "{{ docker_compose_state }}"
    restarted: "{{ docker_compose_restarted }}"
    scale: "{{ docker_compose_service_scale }}"
  when: docker_compose_run_only_pull_images|bool != true
