---

- name: "Checking if configuration for '{{ service }}' exist"
  stat:
    path: "{{ docker_compose_run_local_common_services_dir }}/{{ service }}"
  register: stat_common_service_result
  delegate_to: 127.0.0.1
  become: no

- name: "Copy configuration for '{{ service }}' service"
  copy:
    src: "{{ docker_compose_run_local_common_services_dir }}/{{ service }}"
    dest: "{{ docker_compose_run_remote_services_dir }}/"
    owner: "root"
    mode: "preserve"
  when: stat_common_service_result.stat.exists


- name: Get list files for service '{{ service }}'
  find:
    path: "{{ docker_compose_run_remote_services_dir }}/{{ service }}"
    recurse: yes
  register: find_list_files
  when: (docker_compose_run_rewrite_list is defined) and (docker_compose_run_rewrite_list|length > 0)

- include_tasks: replace-variables.yml
  loop: "{{ find_list_files.files }}"
  loop_control:
    loop_var: item_file
  when: (docker_compose_run_rewrite_list is defined) and (docker_compose_run_rewrite_list|length > 0)


- name: Only pull images for {{ service }}
  shell: |
    cd "{{ docker_compose_run_remote_services_dir }}/{{ service }}"
    docker-compose pull
  when: docker_compose_run_only_pull_images|bool == true

- name: Run service '{{ service }}'
  docker_compose:
    project_src: "{{ docker_compose_run_remote_services_dir }}/{{ service }}"
    state: "{{ docker_compose_state }}"
    restarted: "{{ docker_compose_restarted }}"
    scale: "{{ docker_compose_service_scale }}"
  when: docker_compose_run_only_pull_images|bool != true
