---

- include_tasks: action-absent.yml
  when: docker_compose_run_action == 'absent' or docker_compose_run_action == 'absent-and-delete'

- include_tasks: action-present.yml
  when: docker_compose_run_action == 'present' or docker_compose_run_action == 'present-and-wait-until-end' or docker_compose_run_action == 'copy'
