---

- name: "Checking if configuration for '{{ service }}' exist"
  stat:
    path: "{{ docker_compose_run_local_services_dir }}/{{ service }}"
  register: stat_common_service_result
  delegate_to: 127.0.0.1
  become: no

# - name: "Copy configuration for '{{ service }}' service"
#   copy:
#     src: "{{ docker_compose_run_local_services_dir }}/{{ service }}"
#     dest: "{{ docker_compose_run_remote_services_dir }}/"
#     owner: "root"
#     mode: "preserve"
#   when: stat_common_service_result.stat.exists

- name: Get list files for service '{{ service }}'
  find:
    path: "{{ docker_compose_run_local_services_dir }}/{{ service }}"
    recurse: yes
  register: find_list_local_files
  delegate_to: 127.0.0.1
  become: no

- name: print debug
  debug:
    msg: "{{ docker_compose_run_local_services_dir }}"

# Если переменная 'docker_compose_run_local_services_dir' задана с начальными './', то удаляем их.
- set_fact:
    local_services_dir_trimmed: "{{ docker_compose_run_local_services_dir | replace('./', '') }}"

- name: print debug
  debug:
    msg: "{{ item.path | replace( local_services_dir_trimmed , '') | replace('/' + service + '/', '') }}"
  loop: "{{ find_list_local_files.files }}"

- name: "Copy template j2 configuration for '{{ service }}' service"
  template:
    src: "{{ item.path }}"
    dest: "{{ docker_compose_run_remote_services_dir }}/{{ service }}/{{ item.path | replace( local_services_dir_trimmed , '') | replace('/' + service + '/', '') }}"
    owner: "root"
    mode: "preserve"
  when: stat_common_service_result.stat.exists
  loop: "{{ find_list_local_files.files }}"


# - name: Get list files for service '{{ service }}'
#   find:
#     path: "{{ docker_compose_run_remote_services_dir }}/{{ service }}"
#     recurse: yes
#   register: find_list_files
#   when: (docker_compose_run_rewrite_list is defined) and (docker_compose_run_rewrite_list|length > 0)

# - name: Include replace-variables.yml
#   include_tasks: replace-variables.yml
#   loop: "{{ find_list_files.files }}"
#   loop_control:
#     loop_var: item_file
#   when: (docker_compose_run_rewrite_list is defined) and (docker_compose_run_rewrite_list|length > 0)


# - name: Only pull images for {{ service }}
#   shell: |
#     cd "{{ docker_compose_run_remote_services_dir }}/{{ service }}"
#     docker-compose pull
#   when: docker_compose_run_only_pull_images|bool == true

# - name: Run service '{{ service }}'
#   docker_compose:
#     project_src: "{{ docker_compose_run_remote_services_dir }}/{{ service }}"
#     state: "{{ docker_compose_state }}"
#     restarted: "{{ docker_compose_restarted }}"
#     scale: "{{ docker_compose_service_scale }}"
#     pull: "{{ docker_compose_pull }}"
#   when: docker_compose_run_only_pull_images|bool != true
